name: Deploy to Kubernetes
on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      
      - id: auth
        name: Authentication to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/k8s-pool/providers/K8s-provider'
          service_account: 'supun-devops@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Docker auth
        run: gcloud auth configure-docker

      - name: Build and push docker image
        run: |
          docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodeappimage:${{ env.IMAGE_TAG }} .
          docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodeappimage:${{ env.IMAGE_TAG }}
        working-directory: ./nodeapp

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init 
        run: terraform init -backend-config="bucket=${{ secrets.GCP_TF_STATE_BUCKET }}" -backend-config="prefix=k8s"
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan \
          -var="region=us-central1" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="container_image=us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/nodeappimage:${{ env.IMAGE_TAG }}" \
          -out=PLAN
        working-directory: ./terraform

      - name: Terraform apply
        run: terraform apply PLAN
        working-directory: ./terraform
